/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ad04_naranjo_antonio;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author anaranjo
 */
public class InterfazGrafica extends javax.swing.JFrame {

    // Atributo para gestionar la BD
    private final ManejadorBaseDatos manejador;
    private final String nombreBaseDatos = "concesionarios";

    /**
     * Creates new form AD04_ANC2526_JFrame
     */
    public InterfazGrafica() {
        // Se inician los componentes de la interfaz
        initComponents();
        // Se ajusta el tamaño de la ventana al contenido
        this.pack();
        // Se centra la ventana en la pantalla (después de pack)
        this.setLocationRelativeTo(null);
        // Se inica el manejador de la base de datos solo  una vez al arrancar la interfaz
        manejador = new ManejadorBaseDatos(this.nombreBaseDatos);
        // Cargamos el combo inicial
        rellenarCombo();
        rellenarComboCoches();
    }

    // Método para rellenar el ComboBox de concesionarios
    private void rellenarCombo() {
        jComboBoxConcesionario.removeAllItems();
        List<Concesionario> lista = manejador.consultarConcesionarios();
        for (Concesionario c : lista) {
            jComboBoxConcesionario.addItem(c);
        }
    }

    // Método para rellenar el ComboBox de coches
    private void rellenarComboCoches() {
        // 1. Limpiamos el combo por si tenía datos previos
        jComboBoxCoches.removeAllItems();

        // 2. Pedimos la lista al manejador
        List<Coche> lista = manejador.consultarCoches();

        // 3. Alimentamos el combo
        for (Coche c : lista) {
            jComboBoxCoches.addItem(c);
        }
    }

    // Método para limpiar los campos de texto del panel concesionario
    private void limpiarCamposConcesionario() {
        jTextFieldCif.setText("");
        jTextFieldNombre.setText("");
        jTextFieldDireccion.setText("");
        jTextFieldProvincia.setText("");
        jTextFieldTelefono.setText("");
        jSpinnerNumTrab.setValue(0);

        // Poner el foco de nuevo en el primer campo CIF concesionario
        jTextFieldCif.requestFocus();
    }

    // Método para limpiar los campos de texto del panel coches
    private void limpiarCamposCoche() {
        jTextFieldMatricula.setText("");
        jTextFieldMarca.setText("");
        jTextFieldModelo.setText("");
        jTextFieldKms.setText("");
        jTextFieldPrecio.setText("");

        // Resetear el ComboBox al primer elemento
        if (jComboBoxConcesionario.getItemCount() > 0) {
            jComboBoxConcesionario.setSelectedIndex(0);
        }

        // Devolver el foco a la Matrícula para el siguiente registro
        jTextFieldMatricula.requestFocus();
    }

    // Método para salir de la aplicación previamente cerrando la base de datos
    private void salir() {
        // Cerrar la base de datos si el objeto manejador no es nulo
        if (manejador != null) {
            manejador.cerraBaseDatos(this.nombreBaseDatos);
        }
        // Cerrar la aplicación por completo
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCif = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldProvincia = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jButtonGuardarConcesionario = new javax.swing.JButton();
        jSpinnerNumTrab = new javax.swing.JSpinner();
        jButtonEliminarConcesionario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldKms = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jComboBoxConcesionario = new javax.swing.JComboBox<>();
        jButtonRegistrarCoche = new javax.swing.JButton();
        jButtonSuprimirCoche = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jComboBoxCoches = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("CONCESIONARIOS");

        jLabel2.setText("CIF");

        jLabel3.setText("Nombre");

        jLabel4.setText("Dirección");

        jLabel5.setText("Provincia");

        jLabel6.setText("Teléfono");

        jLabel7.setText("Núm. Trab.");

        jTextFieldCif.setToolTipText("12345678A");

        jTextFieldNombre.setToolTipText("Nombre concesionario");

        jTextFieldDireccion.setToolTipText("Dirección concesionario");

        jTextFieldProvincia.setToolTipText("Provincia");

        jTextFieldTelefono.setToolTipText("123456789");

        jButtonGuardarConcesionario.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonGuardarConcesionario.setText("Guardar");
        jButtonGuardarConcesionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarConcesionarioActionPerformed(evt);
            }
        });

        jSpinnerNumTrab.setModel(new javax.swing.SpinnerNumberModel());
        jSpinnerNumTrab.setToolTipText("Número de trabajadores");

        jButtonEliminarConcesionario.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonEliminarConcesionario.setText("Eliminar");
        jButtonEliminarConcesionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarConcesionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDireccion)
                            .addComponent(jTextFieldProvincia)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCif, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerNumTrab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldNombre)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addComponent(jButtonEliminarConcesionario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGuardarConcesionario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinnerNumTrab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardarConcesionario)
                    .addComponent(jButtonEliminarConcesionario))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("COCHES");

        jLabel9.setText("Matrícula");

        jLabel10.setText("Marca");

        jLabel11.setText("Modelo");

        jLabel12.setText("Kilómetros");

        jLabel13.setText("Precio");

        jLabel14.setText("Concesionario");

        jTextFieldMatricula.setToolTipText("1234 ABC");

        jTextFieldMarca.setToolTipText("Marca vehículo");

        jTextFieldModelo.setToolTipText("Modelo vehículo");

        jTextFieldKms.setToolTipText("Tipo dato Long");

        jTextFieldPrecio.setToolTipText("Tipo dato Double");

        jButtonRegistrarCoche.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonRegistrarCoche.setText("Registrar");
        jButtonRegistrarCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarCocheActionPerformed(evt);
            }
        });

        jButtonSuprimirCoche.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonSuprimirCoche.setText("Suprimir");
        jButtonSuprimirCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuprimirCocheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonSuprimirCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRegistrarCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(jTextFieldModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(jComboBoxConcesionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldKms, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldKms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBoxConcesionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrarCoche)
                    .addComponent(jButtonSuprimirCoche))
                .addContainerGap())
        );

        jButtonSalir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jComboBoxCoches, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalir)
                    .addComponent(jComboBoxCoches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarConcesionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarConcesionarioActionPerformed
        // TODO add your handling code here:

        try {
            // Obtener y validar que no haya campos de texto vacíos
            String cif = jTextFieldCif.getText().trim().toUpperCase();
            String nombre = jTextFieldNombre.getText().trim();
            String dir = jTextFieldDireccion.getText().trim();
            String prov = jTextFieldProvincia.getText().trim();
            String tel = jTextFieldTelefono.getText().trim();
            int numTrab = (Integer) jSpinnerNumTrab.getValue();

            // Comprobar si los campos de textos están vacios y lanzar la excepción si fuera necesario
            if (cif.isEmpty() || nombre.isEmpty() || dir.isEmpty() || prov.isEmpty() || tel.isEmpty()) {
                throw new IllegalArgumentException("Todos los campos de texto son obligatorios.");
            }

            // Validar el CIF del concesionario con un formato adecuado según empresas españolas
            if (!cif.matches("^[ABCDEFGHJNPQRSUVW][0-9]{7}[A-J0-9]$")) {
                throw new IllegalArgumentException("El formato del CIF no es válido. Debe empezar por letra, seguido de 7 números y terminar en letra o número.");
            }

            // Validar el número de teléfono
            if (!tel.matches("[0-9]{9}")) {
                throw new IllegalArgumentException("El teléfono debe tener exactamente 9 dígitos numéricos.");
            }

            // Intento de registro en la base de datos
            manejador.registrarConcesionario(cif, nombre, dir, prov, tel, numTrab);
            // Registro con éxito
            JOptionPane.showMessageDialog(this, "Concesionario " + nombre + " guardado con éxito.");
            rellenarCombo();
            limpiarCamposConcesionario();

        } catch (IllegalArgumentException ex) {
            // Capturar errores de validación previa (campos vacíos, formato número)
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de validación", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalStateException ex) {
            // Capturar el error de CIF ya registrado en la base de datos
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error: CIF ya registrado", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            // Capturar errores genéricos no esperados
            JOptionPane.showMessageDialog(this, "Error inesperado: " + ex.getMessage(), "Error Crítico", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarConcesionarioActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_formWindowClosing

    private void jButtonRegistrarCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarCocheActionPerformed
        // TODO add your handling code here:
        try {
            // Obtener y limpiar datos básicos
            String matricula = jTextFieldMatricula.getText().trim().toUpperCase();
            String marca = jTextFieldMarca.getText().trim();
            String modelo = jTextFieldModelo.getText().trim();

            // Comprobar si los campos de textos están vacios y lanzar la excepción si fuera necesario
            if (matricula.isEmpty() || marca.isEmpty() || modelo.isEmpty()) {
                throw new IllegalArgumentException("Todos los campos de texto son obligatorios.");
            }

            // Validar Matrícula (4 números, espacio, 3 letras permitidas para las matrículas de vehículos en España)
            if (!matricula.matches("^[0-9]{4}\\s[BCDFGHJKLMNPRSTVWXYZ]{3}$")) {
                throw new IllegalArgumentException("Formato de matrícula incorrecto (Ej: 1234 BBB)");
            }

            // Validar Kilómetros
            Long kms;
            try {
                kms = Long.parseLong(jTextFieldKms.getText().trim());
                if (kms <= 0) {
                    throw new IllegalArgumentException("Los kilómetros deben ser mayores a 0.");
                }
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException("Kilómetros: debe introducir un número entero largo.");
            }

            // Validar Precio
            Double precio;
            try {
                precio = Double.parseDouble(jTextFieldPrecio.getText().trim().replace(",", "."));
                if (precio <= 0) {
                    throw new IllegalArgumentException("El precio debe ser mayor a 0.");
                }
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException("Precio: debe introducir un número decimal válido.");
            }

            // Obtener Concesionario del ComboBox
            Concesionario conceSeleccionado = (Concesionario) jComboBoxConcesionario.getSelectedItem();
            if (conceSeleccionado == null) {
                throw new IllegalArgumentException("Debe seleccionar un concesionario de la lista.");
            }

            // Se intenta registrar el vehículo
            manejador.registrarCoche(matricula, marca, modelo, kms, precio, conceSeleccionado);

            JOptionPane.showMessageDialog(this, "Vehículo registrado correctamente.");
            rellenarComboCoches();
            limpiarCamposCoche(); // Deberás crear este método similar al de concesionarios

        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de validación", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalStateException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de duplicado", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + ex.toString());
        }
    }//GEN-LAST:event_jButtonRegistrarCocheActionPerformed

    private void jButtonEliminarConcesionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarConcesionarioActionPerformed
        // TODO add your handling code here:
        try {
            String cif = jTextFieldCif.getText().trim().toUpperCase();
            if (cif.isEmpty()) {
                throw new IllegalArgumentException("Debe indicar el CIF del concesionario a borrar.");
            }

            // Confirmación para eliminar el concesionario
            int respuesta = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de que desea eliminar el concesionario " + cif + "?",
                    "Confirmar borrado", JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {

                manejador.borrarConcesionario(cif);

                JOptionPane.showMessageDialog(this, "Concesionario eliminado correctamente.");

                // Se actualiza la interfaz
                rellenarCombo();
                limpiarCamposConcesionario();
            }

        } catch (IllegalStateException ex) {
            // Captar el error si el concesionario tiene coches
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Restricción de borrado", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + ex.getMessage());
        }

    }//GEN-LAST:event_jButtonEliminarConcesionarioActionPerformed

    private void jButtonSuprimirCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuprimirCocheActionPerformed
        // TODO add your handling code here:
        try {
            String matricula = jTextFieldMatricula.getText().trim().toUpperCase();

            // Validación básica: campo vacío
            if (matricula.isEmpty()) {
                throw new IllegalArgumentException("Por favor, introduzca la matrícula del coche a eliminar.");
            }

            // Confirmación para eliminar el coche
            int respuesta = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de que desea eliminar el coche " + matricula + "?",
                    "Confirmar borrado", JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {

                manejador.borrarCoche(matricula);

                String msg = "Coche con matrícula " + matricula + "eliminado correctamente.";
                System.out.println(msg);
                JOptionPane.showMessageDialog(this, msg);

                // Limpiar los campos del panel de coches
                rellenarComboCoches();
                limpiarCamposCoche();
            }

        } catch (IllegalStateException ex) {
            // Error si el coche no existe
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de borrado", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            // Error si el campo está vacío
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Atención", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + ex.toString());
        }
    }//GEN-LAST:event_jButtonSuprimirCocheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminarConcesionario;
    private javax.swing.JButton jButtonGuardarConcesionario;
    private javax.swing.JButton jButtonRegistrarCoche;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSuprimirCoche;
    private javax.swing.JComboBox<Coche> jComboBoxCoches;
    private javax.swing.JComboBox<Concesionario> jComboBoxConcesionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinnerNumTrab;
    private javax.swing.JTextField jTextFieldCif;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldKms;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldProvincia;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
